services:
  postgres:
    image: postgres:16-alpine
    container_name: chatbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: assistjur
      POSTGRES_PASSWORD: assistjur123
      POSTGRES_DB: bd_assistjur
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
